# Generated by Django 2.1.3 on 2018-12-05 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('type', models.CharField(blank=True, choices=[('Served', 'Served'), ('Burned', 'Burned')], max_length=25, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Trainer')),
            ],
        ),
    ]
