# Generated by Django 2.1.3 on 2019-01-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week',
        ),
    ]
