# Generated by Django 2.1.3 on 2019-01-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_delete_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateTimeField()),
                ('end_day', models.DateTimeField()),
            ],
        ),
    ]
