# Generated by Django 2.1.3 on 2018-12-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181205_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='pin',
            field=models.CharField(blank=True, default='None', max_length=4, null=True),
        ),
    ]
